package com.example.unit_coverter.ui.theme

import androidx.compose.ui.graphics.Color

// ─────────────────────────────────────────────────────────────────────────────
// Brand palette — a refined indigo primary with a muted blue-grey secondary and
// a soft mauve tertiary. Used when Material You dynamic color is unavailable or
// disabled. Full tonal set so surfaces, containers and outlines stay cohesive.
// ─────────────────────────────────────────────────────────────────────────────

// ── Light ────────────────────────────────────────────────────────────────────
val md_light_primary = Color(0xFF4A5AB9)
val md_light_onPrimary = Color(0xFFFFFFFF)
val md_light_primaryContainer = Color(0xFFDEE0FF)
val md_light_onPrimaryContainer = Color(0xFF00105C)
val md_light_secondary = Color(0xFF5A5D72)
val md_light_onSecondary = Color(0xFFFFFFFF)
val md_light_secondaryContainer = Color(0xFFDFE1F9)
val md_light_onSecondaryContainer = Color(0xFF171B2C)
val md_light_tertiary = Color(0xFF76546E)
val md_light_onTertiary = Color(0xFFFFFFFF)
val md_light_tertiaryContainer = Color(0xFFFFD7F3)
val md_light_onTertiaryContainer = Color(0xFF2C1229)
val md_light_error = Color(0xFFBA1A1A)
val md_light_onError = Color(0xFFFFFFFF)
val md_light_errorContainer = Color(0xFFFFDAD6)
val md_light_onErrorContainer = Color(0xFF410002)
val md_light_background = Color(0xFFFBF8FF)
val md_light_onBackground = Color(0xFF1B1B21)
val md_light_surface = Color(0xFFFBF8FF)
val md_light_onSurface = Color(0xFF1B1B21)
val md_light_surfaceVariant = Color(0xFFE3E1EC)
val md_light_onSurfaceVariant = Color(0xFF46464F)
val md_light_outline = Color(0xFF767680)
val md_light_outlineVariant = Color(0xFFC7C5D0)
val md_light_inverseSurface = Color(0xFF303036)
val md_light_inverseOnSurface = Color(0xFFF2EFF7)
val md_light_inversePrimary = Color(0xFFBAC3FF)
val md_light_scrim = Color(0xFF000000)
val md_light_surfaceBright = Color(0xFFFBF8FF)
val md_light_surfaceDim = Color(0xFFDBD9E0)
val md_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_light_surfaceContainerLow = Color(0xFFF5F2FA)
val md_light_surfaceContainer = Color(0xFFEFEDF4)
val md_light_surfaceContainerHigh = Color(0xFFE9E7EF)
val md_light_surfaceContainerHighest = Color(0xFFE4E1E9)

// ── Dark ─────────────────────────────────────────────────────────────────────
val md_dark_primary = Color(0xFFBAC3FF)
val md_dark_onPrimary = Color(0xFF16277B)
val md_dark_primaryContainer = Color(0xFF313F93)
val md_dark_onPrimaryContainer = Color(0xFFDEE0FF)
val md_dark_secondary = Color(0xFFC3C5DD)
val md_dark_onSecondary = Color(0xFF2C2F42)
val md_dark_secondaryContainer = Color(0xFF424659)
val md_dark_onSecondaryContainer = Color(0xFFDFE1F9)
val md_dark_tertiary = Color(0xFFE5BAD8)
val md_dark_onTertiary = Color(0xFF44263E)
val md_dark_tertiaryContainer = Color(0xFF5D3C55)
val md_dark_onTertiaryContainer = Color(0xFFFFD7F3)
val md_dark_error = Color(0xFFFFB4AB)
val md_dark_onError = Color(0xFF690005)
val md_dark_errorContainer = Color(0xFF93000A)
val md_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_dark_background = Color(0xFF121218)
val md_dark_onBackground = Color(0xFFE4E1E9)
val md_dark_surface = Color(0xFF121218)
val md_dark_onSurface = Color(0xFFE4E1E9)
val md_dark_surfaceVariant = Color(0xFF46464F)
val md_dark_onSurfaceVariant = Color(0xFFC7C5D0)
val md_dark_outline = Color(0xFF90909A)
val md_dark_outlineVariant = Color(0xFF46464F)
val md_dark_inverseSurface = Color(0xFFE4E1E9)
val md_dark_inverseOnSurface = Color(0xFF303036)
val md_dark_inversePrimary = Color(0xFF4A5AB9)
val md_dark_scrim = Color(0xFF000000)
val md_dark_surfaceBright = Color(0xFF38383E)
val md_dark_surfaceDim = Color(0xFF121218)
val md_dark_surfaceContainerLowest = Color(0xFF0D0E13)
val md_dark_surfaceContainerLow = Color(0xFF1B1B21)
val md_dark_surfaceContainer = Color(0xFF1F1F25)
val md_dark_surfaceContainerHigh = Color(0xFF29292F)
val md_dark_surfaceContainerHighest = Color(0xFF34343A)
